import type { Metadata } from "next";
import "./globals.css";

const a = require('url')
// a.Url = a.URL
a.URL = a.Url

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <div id="pdf"></div>
      </body>
    </html>
  );
}
